spring:
  application:
    name: ToolsRental
  datasource:
    url: jdbc:postgresql://localhost:5432/tools_rental
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8000

debug: true
